import type { Metadata } from "next";
import {
  DM_Sans,
  Geist,
  Geist_Mono,
  Roboto,
  Tiro_Devanagari_Hindi,
} from "next/font/google";
import "./globals.css";

const dm_sans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const devanagari = Tiro_Devanagari_Hindi({
  weight: "400",
  variable: "--font-tiro",
  subsets: ["devanagari"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm_sans.variable} ${dm_sans.className} ${devanagari.className} ${devanagari.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
