import type { Metadata } from "next";
import {
  DM_Sans,
  Geist,
  Geist_Mono,
  Poppins,
  Roboto,
  Tiro_Devanagari_Hindi,
} from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin", "devanagari"],
  weight: "400",
});

// const dm_sans = DM_Sans({
//   variable: "--font-sans",
//   subsets: ["latin"],
// });

// const devanagari = Tiro_Devanagari_Hindi({
//   weight: "400",
//   variable: "--font-tiro",
//   subsets: ["devanagari"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${poppins.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
