// lib/districts.ts
export const districts = [
  "Agra",
  "Aligarh",
  "Ambedkar Nagar",
  "Amethi",
  "Amroha",
  "Auraiya",
  "Azamgarh",
  "Baghpat",
  "Bahraich",
  "Ballia",
  "Balrampur",
  "Banda",
  "Barabanki",
  "Bareilly",
  "Basti",
  "Bhadohi",
  "Bijnor",
  "Budaun",
  "Bulandshahr",
  "Chandauli",
  "Chitrakoot",
  "Deoria",
  "Etah",
  "Etawah",
  "Farrukhabad",
  "Fatehpur",
  "Firozabad",
  "Gautam Buddha Nagar",
  "Ghaziabad",
  "Ghazipur",
  "Gonda",
  "Gorakhpur",
  "Hamirpur",
  "Hapur",
  "Hardoi",
  "Hathras",
  "Jalaun",
  "Jaunpur",
  "Jhansi",
  "Kannauj",
  "Kanpur Dehat",
  "Kanpur Nagar",
  "Kasganj",
  "Kaushambi",
  "Kushinagar",
  "Lakhimpur Kheri",
  "Lalitpur",
  "Lucknow",
  "Maharajganj",
  "Mahoba",
  "Mainpuri",
  "Mathura",
  "Mau",
  "Meerut",
  "Mirzapur",
  "Moradabad",
  "Muzaffarnagar",
  "Pilibhit",
  "Pratapgarh",
  "Prayagraj",
  "Raebareli",
  "Rampur",
  "Saharanpur",
  "Sambhal",
  "Sant Kabir Nagar",
  "Shahjahanpur",
  "Shamli",
  "Shravasti",
  "Siddharthnagar",
  "Sitapur",
  "Sonbhadra",
  "Sultanpur",
  "Unnao",
  "Varanasi",
];

export const districtHindiMap: { [key: string]: string } = {
  Agra: "आगरा",
  Aligarh: "अलीगढ़",
  "Ambedkar Nagar": "अंबेडकर नगर",
  Amethi: "अमेठी",
  Amroha: "अमरोहा",
  Auraiya: "औरैया",
  Azamgarh: "आजमगढ़",
  Baghpat: "बागपत",
  Bahraich: "बहराइच",
  Ballia: "बलिया",
  Balrampur: "बलरामपुर",
  Banda: "बांदा",
  Barabanki: "बाराबंकी",
  Bareilly: "बरेली",
  Basti: "बस्ती",
  Bhadohi: "भदोही",
  Bijnor: "बिजनौर",
  Budaun: "बदायूं",
  Bulandshahr: "बुलंदशहर",
  Chandauli: "चंदौली",
  Chitrakoot: "चित्रकूट",
  Deoria: "देवरिया",
  Etah: "एटा",
  Etawah: "इटावा",
  Farrukhabad: "फर्रुखाबाद",
  Fatehpur: "फतेहपुर",
  Firozabad: "फिरोजाबाद",
  "Gautam Buddha Nagar": "गौतम बुद्ध नगर",
  Ghaziabad: "गाजियाबाद",
  Ghazipur: "गाजीपुर",
  Gonda: "गोंडा",
  Gorakhpur: "गोरखपुर",
  Hamirpur: "हमीरपुर",
  Hapur: "हापुड़",
  Hardoi: "हरदोई",
  Hathras: "हाथरस",
  Jalaun: "जालौन",
  Jaunpur: "जौनपुर",
  Jhansi: "झांसी",
  Kannauj: "कन्नौज",
  "Kanpur Dehat": "कानपुर देहात",
  "Kanpur Nagar": "कानपुर नगर",
  Kasganj: "कासगंज",
  Kaushambi: "कौशाम्बी",
  Kushinagar: "कुशीनगर",
  "Lakhimpur Kheri": "लखीमपुर खीरी",
  Lalitpur: "ललितपुर",
  Lucknow: "लखनऊ",
  Maharajganj: "महराजगंज",
  Mahoba: "महोबा",
  Mainpuri: "मैनपुरी",
  Mathura: "मथुरा",
  Mau: "मऊ",
  Meerut: "मेरठ",
  Mirzapur: "मिर्जापुर",
  Moradabad: "मुरादाबाद",
  Muzaffarnagar: "मुजफ्फरनगर",
  Pilibhit: "पीलीभीत",
  Pratapgarh: "प्रतापगढ़",
  Prayagraj: "प्रयागराज",
  Raebareli: "रायबरेली",
  Rampur: "रामपुर",
  Saharanpur: "सहारनपुर",
  Sambhal: "संभल",
  "Sant Kabir Nagar": "संत कबीर नगर",
  Shahjahanpur: "शाहजहांपुर",
  Shamli: "शामली",
  Shravasti: "श्रावस्ती",
  Siddharthnagar: "सिद्धार्थनगर",
  Sitapur: "सीतापुर",
  Sonbhadra: "सोनभद्र",
  Sultanpur: "सुल्तानपुर",
  Unnao: "उन्नाव",
  Varanasi: "वाराणसी",
};
